---
- name: configure system bash
  copy:
    src: 10-bash_profile.sh
    dest: /etc/profile.d/10-bash_profile.sh
    mode: 0755
  become: yes

- name: dotfiles
  copy:
    src: "{{ item }}"
    dest: "/home/{{ ansible_user_id }}/.{{ item }}"
  with_items:
    - tmux.conf
    - vimrc
    - bash_aliases
