---
- name: load components
  include_tasks: "{{ task_item }}.yaml"
  with_items:
    - resolved
    - journald
    - timesyncd
    - coredump
  loop_control:
    loop_var: task_item

- name: flush handlers
  meta: flush_handlers
