---
- name: install Logrotate
  package:
    name: logrotate
    state: present
  become: yes

# This does not need to "restart" the timer. The daemon-reload will do that.
- name: configure timer
  copy:
    src: logrotate.timer
    dest: /etc/systemd/system/logrotate.timer
  become: yes
  notify: reload systemd
