---
- name: Configure user limits
  copy:
    dest: /etc/security/limits.d/10-twitarr.conf
    content: |
      #
      # Managed by Ansible
      #
      {{ ansible_user_id }} soft nofile 10000
  become: yes
