---
- name: allow ports
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  become: yes
  with_items:
    - '80'
    - '8080'
    - '9100'
    - '8081'

# This clutters up dmesg
- name: disable logging
  ufw:
    logging: 'off'
  become: yes
