---
- name: allow ports
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  become: yes
  with_items:
    - '22'
    - '80'
    - '8080'
    - '9100'
    - '8081'

- name: enable firewall
  ufw:
    state: enabled
    policy: deny

# This clutters up dmesg
- name: disable logging
  ufw:
    logging: 'off'
  become: yes

# Needed for systemd-resolved to work
- name: allow dns for systemd-resolved
  ufw:
    rule: allow
    port: '53'
    proto: udp
    src: 172.17.0.0/16
  become: yes
