---
- name: purge snap
  snap:
    name: docker
    state: absent
  become: yes

- name: install repo dependencies
  package:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
  become: yes

- name: repository key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: yes

- name: repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present
  become: yes

- name: install docker
  package:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: present
  become: yes

- name: create config directory
  file:
    path: /etc/docker
    state: directory
    mode: 0755
  become: yes

- name: configure daemon
  copy:
    content: "{{ docker_daemon_config | to_nice_json }}"
    dest: /etc/docker/daemon.json
    backup: yes
  become: yes
  notify:
    - restart docker

- import_role:
    name: logrotate
    tasks_from: docker

- name: enable service
  service:
    name: docker
    state: started
    enabled: yes
  become: yes

- name: configure legacy plugin access
  file:
    src: /usr/libexec/docker/cli-plugins/docker-compose
    dest: /usr/local/bin/docker-compose
    state: link
  become: yes
