---
- name: Install Docker
  package:
    name:
      - docker
      - docker-compose
    state: present
  become: yes

- name: Create config directory
  file:
    path: /etc/docker
    state: directory
    mode: 0755
  become: yes

- name: Configure Docker daemon
  copy:
    content: "{{ docker_daemon_config | to_nice_json }}"
    dest: /etc/docker/daemon.json
    backup: yes
  become: yes
  notify:
    - restart docker

- import_role:
    name: logrotate
    tasks_from: docker

- name: Enable service
  service:
    name: docker
    state: started
    enabled: yes
  become: yes
