---
- name: create directories
  file:
    path: "{{ item }}"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    state: directory
  become: yes
  with_items:
    - "{{ twitarr_root_dir }}"

- name: create log directory
  file:
    path: "{{ twitarr_logs_dir }}"
    owner: "{{ ansible_user_id }}"
    group: adm
    state: directory
    mode: 0775
  become: yes
  notify: restart rsyslog

- name: install development dependencies
  package:
    name:
      - libgd-dev
      - libjpeg-dev
    state: present
  become: yes

- name: clone source
  git:
    repo: "https://github.com/jocosocial/swiftarr"
    dest: "{{ twitarr_src_dir }}"
    version: master

- name: clone deploy
  git:
    repo: "github.com:jocosocial/twitarr-prod"
    dest: "{{ twitarr_deploy_dir }}"
    key_file: "/home/{{ ansible_user_id }}/.ssh/deploy"
